spring:
  config:
    import:
      - optional:file:env/aws.env[.properties]

cloud:
  aws:
    s3:
      bucket: ${AWS_BUCKET_NAME}
      region: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}